#!/bin/bash -f
#
# Path Jumper - Jump to a directory in the path that starts with targ. Case-insensitive and supports fuzzy matching
#               Needs ruby

unset -f jumper
jumper() {
  if (($# == 0)); then
    echo "ERROR: Insufficient number of arguments"
    echo "SYNTAX: path_jump <dir>"
  fi

  #echo "Jumping to a parent dir in the path"
  local _targ=${1/%\//}
  # Remove spaces, escape any bare dots and add fuzzy magic
  local _rx=$(ruby -e "print '${_targ}'.gsub(/\s+/,'').split('').join('.*?').gsub(/\.(?!\*\?)/,'\.')")
  #echo Matched: $_rx
  echo $PWD | ruby -e "print STDIN.read.sub(/(.*\/${_rx}[^\/]*\/).*/i,'\1')"

  # Plain-old jumping, no fuzziness
  #_dir=$(echo $PWD | sed "s,\(^.*$2[^/]*\)/.*$,\1,")
  #echo ${_dir}
}
