#!/usr/bin/perl
#
# Perl Script to fire a single LSF Job by prompting for options
# Supported switches are
#  -P  : Defaults to P0:IO_10015123
#  -q  : Short, Normal, Regress, Gui (with -I option). Defaults to short
#  -R  : Option to specify OS and Mem option. Defaults to "select[ws40]"
#  -sp : Priority, omitted unless specified
#  -J  : Omitted unless specified
#  -o  : Specify output file. Omitted by default. If selected and name not give, defaults to lsf.out
#
#==================================================================================================#

use strict;
use diagnostics;
use constant DEBUG=>0;


my $flag=0;


print "\nTo use default values wherever available, press Enter\n";

#=== Command ======================================================================================#

print "   Enter Command : "; chomp($_=<>);
s{\bspice\b}{/apps/ame/bin/spice3}g;
s{\bhspice\b}{/apps/ame/bin/hspice}g;

my $command = $_;
print "\nCOMMAND = $command\n\n\n" if(DEBUG==1);



#=== Job Name =====================================================================================#

print "   Enter Job Name : "; chomp($_=<>);
my $log = $_.".lsf.out";

my $jobname = "-J $_" unless($_ eq "");

print "\nJOB = $jobname\n\n\n" if(DEBUG==1);



#=== Queue Selection ==============================================================================#
my $I="";
my $queue;

do{
	print "   Select Queue (default=short)\n" unless ($flag);
	print "      Options : s(hort)/n(ormal)/r(egress)/g(ui) : "; chomp($_=<>);
	
	$flag=0;	
	if (/s(hort)?/i||""){
		$queue="-q short";
	}elsif(/n(ormal)?/i){
		$queue="-q normal";
	}elsif(/r(egress)?/i){
		$queue="-q regress";
	}elsif(/g(ui)?/i){
		$queue="-q gui";
		print "      Is it Interactive? (y/n) (default:No) : "; chomp($_=<>);
		$I="-I" if(/y(es)?/);
	}else{
		print "      Invalid queue. Select from the specified options or press Enter to skip : \n";
		$flag=1;
	}
}while($flag);

print "\nQUEUE = $queue" if(DEBUG==1);
print "\nINTERACTIVE = $I\n\n\n" if(DEBUG==1);



#=== Priority Selection ===========================================================================#

do{
	print "   Select Priority. Type just the number (default:omitted) : "; chomp($_=<>);
	print "      Invalid input. Enter an integer between 0 and 100 or press Enter to skip.\n" unless ((/^\d+$/)&&($_>=0)&&($_<=100)||($_ eq ""));
}while(!((/^\d+$/)&&($_>=0)&&($_<=100)||($_ eq "")));

my $priority = ($_ eq "" ? "" : "-sp $_");

print "\nPRIORITY = $priority\n\n\n" if(DEBUG==1);



#=== Resource Selection ===========================================================================#

print "   Select Machine. Type name with quotes (default=ws40) : "; chomp(my $os=<>);
print "   Specify Memory Requirement (default:omitted) : "; chomp(my $mem=<>);
print "   Specify reservation parameters (default:omitted) : "; chomp(my $rusage=<>);

$os  = ($os eq "" ? "ws40" : "$os");
$mem = " && mem>$mem" if($mem ne "");
$rusage = "rusage[$rusage]" if($rusage ne "");
my $resource = sprintf("-R \"select[%s%s] $rusage\"",${os},${mem});

print "\nRESOURCE = $resource\n\n\n" if(DEBUG==1);



#=== Project Name =================================================================================#

print "   Enter Project Name (default:P0:IO_10015123) : "; chomp($_=<>);
my $proj= ($_ eq "" ? "-P P0:IO_10015123" : "-P $_");

print "\nPROJ = $proj\n\n\n" if(DEBUG==1);



#=== Output File ==================================================================================#

print "   Save Log? (default:Yes) : "; chomp($_=<>);
if ((/y(es)?/i)||($_ eq "")){
	print "      Specify name of log file (default:$log) : "; chomp($_=<>);
	$log = ($_ eq "" ? "-o $log" : "-o $_");
}else{
	$log = "";
}
print "\nLOG = $log\n\n\n" if(DEBUG==1);



#==================================================================================================#

my $lsfcommand = "/usr/local/lsf/bin/bsub $proj $queue $I $resource $priority $jobname $log $command";
$lsfcommand =~ s/\s+/ /g;

print "\nCommand :\n   $lsfcommand";

print "\n\nExecute? (default:No) : "; chomp($_=<>);
system("$lsfcommand") if(/y(es)?/i);
