#!/bin/sh
if [ -z $REPO_PATH ]; then
  echo "REPO_PATH is unset!"
  exit 1
fi

# Directories to search
tag_dirs=($REPO_PATH/libs/verif $REPO_PATH/ch)
tags_db=$REPO_PATH/.tags
export CSCOPE_DB=$REPO_PATH/.cscope.out

# Clean up temp files
rm -f $tags_db $CSCOPE_DB

# Find files
find ${tag_dirs[@]} -type f \( -iname "*.h" -or -iname "*.cc" -or -iname "*.c" -or -iname "*.cpp" -or -iname "*.C" -or -iname "*.v" -or -iname "*.sv" -or -iname "*.svh" -or -iname "*.x" \) >| $REPO_PATH/tags.filelist
#find ${tag_dirs[@]} -type f \( -iname "*.h" -or -iname "*.cc" \) >| $REPO_PATH/tags.filelist

# Follow symlinks for generates files
find ${tag_dirs[@]} -type l \( -iname "*.h" -or -iname "*.cc" -or -iname "*.c" -or -iname "*.cpp" -or -iname "*.C" -or -iname "*.v" -or -iname "*.sv" -or -iname "*.svh" -or -iname "*.x" \) -exec readlink '{}' \; >> $REPO_PATH/tags.filelist
#find ${tag_dirs[@]} -type l \( -iname "*.h" -or -iname "*.cc" \) -exec readlink '{}' \; >> $REPO_PATH/tags.filelist

/tool/pandora64/latest/bin/ctags --languages=c++ --c++-kinds=+p --fields=+Sail --extra=+q -L $REPO_PATH/tags.filelist -f $tags_db 2> /dev/null &
cscope -bqk -i $REPO_PATH/tags.filelist -f $CSCOPE_DB 2> /dev/null &

wait
rm -f $REPO_PATH/tags.filelist ${CSCOPE_DB}{.in, .po}


# Reset Cscope DB in vim
command vim --serverlist | command grep -i $REPO_PATH | command xargs -n1 -I{} vim --servername {} --remote-send ':cscope reset<CR>'
